name: FETCHER
on:
  repository_dispatch:
    types: [fetch]
jobs:
  fetching:
    runs-on: ubuntu-latest
    env:
      pageid: ${{ github.event.client_payload.pageid }}
    steps:
      - name: Chekcout
        uses: actions/checkout@v4
      - name: Run fetch
        run: |
          cd program
          echo $(ls)
          echo ${{ toJson(github.event.client_payload) }}
          chmod 755 fetcher.sh
          ./fetcher.sh "$pageid"
          git add .
          git commit -m 'halaman baru'
          git push
