on:
  repository_dispatch:
    types: [fetch]
jobs:
  fetching:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout
        uses: actions/checkout@v4
      - name: Run fetch
        run: |
          cd docs/
          echo ${{ toJson(github.event.client_payload) }}
          ./fetch.sh ${{ github.event.client_payload.pageid }}
