name: FETCHER
on:
  repository_dispatch:
    types: [fetch]
jobs:
  fetching:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout
        uses: actions/checkout@v4
      - name: Run fetch
        working-directory: program
        shell: bash
        run: |
          git config --global user.email "opssd3klaling@gmail.com"
          git config --global user.name "abilz"
          ./fetcher.sh ${{ toJson(github.event.client_payload.pageid) }}
          git add .
          git commit -m 'halaman baru'
          git push
